### ISSUE TITLE
A question about the BiO-Net++

### ISSUE THREAD

**Issue by Ifjmww** [tiangexiang/BiX-NAS#3]
Dear author：

    Your team has made great contributions to the development of medical image segmentation, such as BiO-Net, BiX-NAS and so on. 
    I have a question about the BiO-Net++. BiO-Net++ adds a lot of dense connections between encode blocks and decode blocks on the basis of BiO-Net. Why is the number of parameters two orders of magnitude less than that of BiO-Net?
![image](https://user-images.githubusercontent.com/46148695/185894328-61d2238d-779f-441e-8e57-2d56ebfd79bf.png)

    Hope to get your answer, thank you very much.

**Comment by MAGNOLIAw** [comment]
Hi, 

We first reduced the computational complexity in BiO-Net by optimizing the feature fusion scheme and feature channel numbers at each level. Such optimizations are adopted in the design of both BiO-Net++ and BiX-Net yielding only 0.43 M trainable parameters. Our Phase1 search algorithm provides a further 8.6% MACs reduction, and our BiX-Net eventually achieves a 20% MACs reduction compared to BiO-Net++. 

If you check the code, you can find that we constrained the channel number for each scale and avoid using concatenation (use weighted addition instead) when fusing the skips. 

Thank you for your question. 

Regards,
